schema: 'src/graphql/type-defs.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - typescript-resolvers
config:
  optionalResolveType: true
respectGitIgnore: true
